baseURL: "http://example.org/"
languageCode: "en-us"
title: "Bootstrap Custom - Hugo"

languageCode: "en"

enableInlineShortcodes: true
enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishDir:             "wwwroot"
